// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFoNLbg8MqM5rTVI_2r7bXAWRf21-ODLI',
    appId: '1:834144857877:web:036e1a3d0e45ae03a9c31c',
    messagingSenderId: '834144857877',
    projectId: 'applogin-8850f',
    authDomain: 'applogin-8850f.firebaseapp.com',
    storageBucket: 'applogin-8850f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8kC5mW2L6uUTaIPIeNVtaNgEV1fjdcfo',
    appId: '1:834144857877:android:9f03eb54641a9a73a9c31c',
    messagingSenderId: '834144857877',
    projectId: 'applogin-8850f',
    storageBucket: 'applogin-8850f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHq2JqvN4wdxOvnPNZCQkdRwh9k9FOeOU',
    appId: '1:834144857877:ios:d1e76fae492b9b18a9c31c',
    messagingSenderId: '834144857877',
    projectId: 'applogin-8850f',
    storageBucket: 'applogin-8850f.appspot.com',
    iosBundleId: 'com.example.applogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHq2JqvN4wdxOvnPNZCQkdRwh9k9FOeOU',
    appId: '1:834144857877:ios:dc10045a6bdc05f7a9c31c',
    messagingSenderId: '834144857877',
    projectId: 'applogin-8850f',
    storageBucket: 'applogin-8850f.appspot.com',
    iosBundleId: 'com.example.applogin.RunnerTests',
  );
}
